const items = [
    {
        id: '001',
        image: 'img/img8.jpg',
        company: 'SALAR',
        item_name: ' HOMBALE FILMS',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'img/img2.jpg',
        company: 'PATHAN',
        item_name: 'YASH RAJ FILMS',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'img/img3.jpg',
        company: 'GAAMI',
        item_name: 'VR GLOBAL MEDIA',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'img/img4.jpg',
        company: 'EAGLE',
        item_name: 'PEOPLE MEDIA FACTORY',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'img/img5.jpg',
        company: 'OMG',
        item_name: 'WAVE CENEMAS , VIACOM18 MOTION PICTURE',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'img/img6.jpg',
        company: 'LEO',
        item_name: 'SEVEN SCREEN STUDIO FILMS',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'img/img7.jpg',
        company: 'JANYA',
        item_name: 'HOMBALE FILMS',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'img/img1.jpg',
        company: 'HOTAM',
        item_name: 'KR STUDIOS',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];